version: '3'

services:
  seeder:
    container_name: bchack_seeder
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    command: "npm run start-seeder"
    ports:
      - "6881-6889"
      - "40001"
    environment:
      DEBUG: '*'

  leecher:
    container_name: bchack_leecher
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    command: "npm run start-leecher"
    environment:
      DEBUG: '*'
