version: '3'

services:
  seeder:
    container_name: bchack_seeder
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    command: "npm run-script start-seeder"

  leecher:
    container_name: bchack_leecher
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    command: "npm run-script start-leecher"
