version: '3'

services:
  seeder:
    container_name: bchack_seeder
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ../:/app
    command: "bash -c 'cd paid_webtorrent && npm run start-seeder'"
    networks:
      net1:
        ipv4_address: 172.5.0.2
        # environment:
        #   DEBUG: '*'
    # network_mode: host

  leecher0:
    container_name: bchack_leecher0
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ../:/app
    command: "bash -c 'sleep 10 && cd paid_webtorrent && npm run start-leecher'"
    networks:
      net1:
        ipv4_address: 172.5.0.3

        # environment:
        #   DEBUG: '*'
    # network_mode: host

  ganache: # XXX: has to be started before any webtorrent client
    container_name: ganache
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ../:/app
    command: "bash -c 'cd playground/local; (sleep 5 && npm run deploy) & (npm run start)'"
    networks:
      net1:
        ipv4_address: 172.5.0.4
        # network_mode: host

        #   dht:
        #     container_name: dht
        #     build:
        #       context: ./
        #       dockerfile: ./Dockerfile
        #     volumes:
        #       - ../:/app
        #     command: "bash -c 'cd paid_webtorrent && npm run start-dht'"
        #     networks:
        #       net1:
        #         ipv4_address: 172.5.0.5


networks:
  net1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.5.0.0/16
          gateway: 172.5.0.1
