version: '3'

services:
  seeder:
    container_name: bchack_seeder
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ../:/app
    command: "bash -c 'cd paid_webtorrent && npm run start-seeder'"
    networks:
      - net1
    # network_mode: host
    # environment:
    #   DEBUG: '*'

  leecher0:
    container_name: bchack_leecher0
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ../:/app
    command: "bash -c 'cd paid_webtorrent && npm run start-leecher'"
    networks:
      - net1

    # network_mode: host
    # environment:
    #   DEBUG: '*'

  ganache:
    container_name: ganache
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ../:/app
    command: "bash -c 'cd playground/local; (sleep 5 && npm run deploy) & (npm run start)'"
    networks:
      - net1

networks:
  net1:
    driver: bridge
